// flow-typed signature: e230119a1b7c692f01e199e127a503f5
// flow-typed version: <<STUB>>/storybook-addon-jsx_v^7.1.2/flow_v0.102.0-rc

/**
 * This is an autogenerated libdef stub for:
 *
 *   'storybook-addon-jsx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'storybook-addon-jsx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'storybook-addon-jsx/lib/__tests__/index.test' {
  declare module.exports: any;
}

declare module 'storybook-addon-jsx/lib/constants' {
  declare module.exports: any;
}

declare module 'storybook-addon-jsx/lib' {
  declare module.exports: any;
}

declare module 'storybook-addon-jsx/lib/jsx' {
  declare module.exports: any;
}

declare module 'storybook-addon-jsx/lib/prism' {
  declare module.exports: any;
}

declare module 'storybook-addon-jsx/lib/register' {
  declare module.exports: any;
}

declare module 'storybook-addon-jsx/lib/theme' {
  declare module.exports: any;
}

declare module 'storybook-addon-jsx/lib/types/react-element-to-jsx-string.d' {
  declare module.exports: any;
}

declare module 'storybook-addon-jsx/lib/types/storybook__components.d' {
  declare module.exports: any;
}

declare module 'storybook-addon-jsx/lib/types/storybook__ui.d' {
  declare module.exports: any;
}

declare module 'storybook-addon-jsx/register' {
  declare module.exports: any;
}

// Filename aliases
declare module 'storybook-addon-jsx/lib/__tests__/index.test.js' {
  declare module.exports: $Exports<
    'storybook-addon-jsx/lib/__tests__/index.test'
  >;
}
declare module 'storybook-addon-jsx/lib/constants.js' {
  declare module.exports: $Exports<'storybook-addon-jsx/lib/constants'>;
}
declare module 'storybook-addon-jsx/lib/index' {
  declare module.exports: $Exports<'storybook-addon-jsx/lib'>;
}
declare module 'storybook-addon-jsx/lib/index.js' {
  declare module.exports: $Exports<'storybook-addon-jsx/lib'>;
}
declare module 'storybook-addon-jsx/lib/jsx.js' {
  declare module.exports: $Exports<'storybook-addon-jsx/lib/jsx'>;
}
declare module 'storybook-addon-jsx/lib/prism.js' {
  declare module.exports: $Exports<'storybook-addon-jsx/lib/prism'>;
}
declare module 'storybook-addon-jsx/lib/register.js' {
  declare module.exports: $Exports<'storybook-addon-jsx/lib/register'>;
}
declare module 'storybook-addon-jsx/lib/theme.js' {
  declare module.exports: $Exports<'storybook-addon-jsx/lib/theme'>;
}
declare module 'storybook-addon-jsx/lib/types/react-element-to-jsx-string.d.js' {
  declare module.exports: $Exports<
    'storybook-addon-jsx/lib/types/react-element-to-jsx-string.d'
  >;
}
declare module 'storybook-addon-jsx/lib/types/storybook__components.d.js' {
  declare module.exports: $Exports<
    'storybook-addon-jsx/lib/types/storybook__components.d'
  >;
}
declare module 'storybook-addon-jsx/lib/types/storybook__ui.d.js' {
  declare module.exports: $Exports<
    'storybook-addon-jsx/lib/types/storybook__ui.d'
  >;
}
declare module 'storybook-addon-jsx/register.js' {
  declare module.exports: $Exports<'storybook-addon-jsx/register'>;
}
