// flow-typed signature: a62a7a8124789a198a714b814de8a0e8
// flow-typed version: <<STUB>>/@storybook/addon-viewport_v^5.1.9/flow_v0.102.0-rc

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-viewport'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-viewport' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-viewport/dist/constants' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/dist/defaults' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/dist/legacy_preview' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/dist/legacy_preview/withViewport' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/dist/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/dist/Tool' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/preview' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/src/constants' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/src/defaults' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/src/legacy_preview' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/src/legacy_preview/withViewport' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/src/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/src/Tool' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-viewport/dist/constants.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/dist/constants'>;
}
declare module '@storybook/addon-viewport/dist/defaults.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/dist/defaults'>;
}
declare module '@storybook/addon-viewport/dist/legacy_preview/index' {
  declare module.exports: $Exports<
    '@storybook/addon-viewport/dist/legacy_preview'
  >;
}
declare module '@storybook/addon-viewport/dist/legacy_preview/index.js' {
  declare module.exports: $Exports<
    '@storybook/addon-viewport/dist/legacy_preview'
  >;
}
declare module '@storybook/addon-viewport/dist/legacy_preview/withViewport.js' {
  declare module.exports: $Exports<
    '@storybook/addon-viewport/dist/legacy_preview/withViewport'
  >;
}
declare module '@storybook/addon-viewport/dist/register.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/dist/register'>;
}
declare module '@storybook/addon-viewport/dist/Tool.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/dist/Tool'>;
}
declare module '@storybook/addon-viewport/preview.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/preview'>;
}
declare module '@storybook/addon-viewport/register.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/register'>;
}
declare module '@storybook/addon-viewport/src/constants.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/src/constants'>;
}
declare module '@storybook/addon-viewport/src/defaults.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/src/defaults'>;
}
declare module '@storybook/addon-viewport/src/legacy_preview/index' {
  declare module.exports: $Exports<
    '@storybook/addon-viewport/src/legacy_preview'
  >;
}
declare module '@storybook/addon-viewport/src/legacy_preview/index.js' {
  declare module.exports: $Exports<
    '@storybook/addon-viewport/src/legacy_preview'
  >;
}
declare module '@storybook/addon-viewport/src/legacy_preview/withViewport.js' {
  declare module.exports: $Exports<
    '@storybook/addon-viewport/src/legacy_preview/withViewport'
  >;
}
declare module '@storybook/addon-viewport/src/register.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/src/register'>;
}
declare module '@storybook/addon-viewport/src/Tool.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/src/Tool'>;
}
